### ISSUE TITLE
Add definition for "warmup" trigger

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-java-library#108]
There's a new trigger for Azure Functions that allows your app to "warmup" before routing traffic during scale operations.  Because in Java apps `function.json` metadata is generated during `mvn package` we need to add an annotation for @WarmupTrigger 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=java

/ cc @kulkarnisonia16 @alexkarcher-msft @amamounelsayed

**Comment by shayannyc25** [comment]
hi
any update on this?
i am trying to create a java azure function like:
    @FunctionName("Warmup")
    public void warmUpFunction(ExecutionContext context){
        try{
            connection = DriverManager.getConnection(connectionUrl);
            context.getLogger().info("EventHubTriggerJavaToSQLDB.WarmUp function executed.");

        }catch (SQLException e) {
            context.getLogger().info("Exception while getting="+e.toString());
            e.printStackTrace();
        }  
    }

and getting error on start up:
The 'Warmup' function is in error: At least one binding must be declared

**Comment by kaibocai** [comment]
resolved by https://github.com/Azure/azure-functions-java-library/pull/183

example like: 

```
@FunctionName("Warmup")
public void warmup(@CustomBinding(direction = "in", name = "warmupContext", type = "warmupTrigger")Object warmupContext, ExecutionContext context) {
    context.getLogger().info("Function App instance is warm up");
}
```
