### ISSUE TITLE
Azure function created by Java is saying “Your app is currently in read only mode because you are running from a package file” , how to resolve it?

### ISSUE THREAD

**Issue by rbhattaqhr** [Azure/azure-functions-java-library#114]
Currently, I'm working on Azure function created by Java. I am able to publish Java function to Azure portal and I'm able to make a GET and POST request but I'm having issue with enabling function in write mode. So, what should I do now?

**Comment by amamounelsayed** [comment]
Hey @rbhattaqhr, currently it is not supported to update your code in the portal. Is that what you are looking for?

Thank you

**Comment by amamounelsayed** [comment]
@rbhattaqhr Do you have any update regarding this?

**Comment by rbhattaqhr** [comment]
Since it is not required for us to enable function in write mode. So, I am good for now. Thanks @amamounelsayed .
