### ISSUE TITLE
Deserialization ignore Gson annotations for a HttpTrigger function

### ISSUE THREAD

**Issue by agilisticdev** [Azure/azure-functions-java-library#127]
I am developing a new Http trigger function in Kotlin. The function is a POST on a certain resource. On of my requirement is to use snake case instead of camel case. Here is the problem I am facing: the deserialization from json -> object completely ignores the @SerializedName annotation (from Gson). It works if my json element names are exactly identical to the class member but does not work - creates an empty object - when I post a json that uses snake case!

Why the Gson annotations are ignored? I tried Jackson annotation @JsonProperty and it ignores them too!

It used to work less than a month ago!!!

**Comment by agilisticdev** [comment]
azure-functions-java-library version 1.3.1

**Comment by agilisticdev** [comment]
It

**Comment by amamounelsayed** [comment]
Hey @agilisticdev, can you please try it with the latest version, we are updating the latest release notes in this issue https://github.com/Azure/azure-functions-java-worker/issues/400
