### ISSUE TITLE
PATCH is missing from HttpMethods

### ISSUE THREAD

**Issue by szirbucz** [Azure/azure-functions-java-library#130]
I would like to create a HTTP trigger for a PATCH request, but I sadly recognized that there is no option for it.

**Comment by Ganwel** [comment]
Is there a specific reason for that? I have the same issue here. Not able to use PATCH with an Azure function

**Comment by cascer1** [comment]
We are also running into this issue.

**Comment by vdlmark** [comment]
This seems like an oversight. Can this be added on short term?

**Comment by kaibocai** [comment]
Add a workaround for this: after build your jar file find the function.json file and change the method to PATCH, then no matter what method type you defined in your functions it will always be treated as a PATCH method. 

example: 
```json
{
  "scriptFile" : "../fabrikam-functions-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.fabrikam.Function.run",
  "bindings" : [ {
    "type" : "httpTrigger",
    "direction" : "in",
    "name" : "req",
    "methods" : [ "PATCH" ],
    "authLevel" : "ANONYMOUS"
  }, {
    "type" : "http",
    "direction" : "out",
    "name" : "$return"
  } ]
}

```

**Comment by leonfau** [comment]
Can you create a new release with the PATCH included?

**Comment by kaibocai** [comment]
Hi @leonfau , thanks for reaching out. The new release will be ready in next month. We also include some new features, right now it's under end to end and regression testing process. Thanks for your understanding.

**Comment by kaibocai** [comment]
This is resolved in current release.
