### ISSUE TITLE
ServiceBusQueueTrigger MessageReceiver Binding throws error

### ISSUE THREAD

**Issue by musa-pro** [Azure/azure-functions-java-library#137]
I was trying to get metadata MessageReceiver for a ServiceBusQueueTrigger function using binding annotation, but this throws error. I noticed MessageSession, DeadletterSource throws error too whereas other binding works well. I was following this document
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=java

Is this expected or what I'm doing wrong?
Here is what I've
```
    @FunctionName("MessageConsumer")
    public void run(
            @ServiceBusQueueTrigger(name = "msg",
                    queueName = "ServiceBusQueue",
                    connection = "ServiceBusConStr")
                    String message,
            @BindingName("MessageReceiver") MessageReceiver messageReceiver,
            @BindingName("UserProperties") Map<String, Object> properties,
            final ExecutionContext context
    ){
        context.getLogger().info("got message from: "+message);
    }
```

**Comment by avs099** [comment]
this worked for me:
```
@BindingName("ApplicationProperties") Map<String, Object> properties,
```

I took binding name from this list: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#message-metadata

**Comment by kaibocai** [comment]
Hi @musa-pro , please use link paste by @avs099 for correct binding name. Thank you @avs099 for the help here 💯 . 
Please reopen this issue if you still has the problem. Thanks.

**Comment by PengChaoSun** [comment]
Hi @avs099, thanks for your sharing, I have the same issue, and tried your suggestion, but not work for me. and the shared link is for C# not Java. attached the code and error logs.
![image](https://github.com/Azure/azure-functions-java-library/assets/6456339/35a2be02-06f6-4bf9-ba96-958c451c18b2)


![image](https://github.com/Azure/azure-functions-java-library/assets/6456339/348ec665-33e3-47ec-87ba-41fba55bcbdd)

**Comment by kaibocai** [comment]
@PengChaoSun , I cannot reproduce your issue with the same code, can you double check if your function is defined correctly? 
<img width="1813" alt="image" src="https://github.com/Azure/azure-functions-java-library/assets/89094811/cec2639f-010b-4625-9018-65c0a0a616f4">
