### ISSUE TITLE
SpringBoot Azure Function

### ISSUE THREAD

**Issue by debinaik** [Azure/azure-functions-java-library#140]
Hi Team,

Could you please confirm , if spring boot azure function supports  below triggers ?

1.IoT HUB Trigger
2.Timer Trigger.

I have encountered issues with timer trigger  and .I am requested to reach this community as per the ticket https://github.com/Azure/azure-sdk-for-java/issues/16355 . Please find the details code reference and communication details at the parent ticket https://github.com/Azure/azure-sdk-for-java/issues/16355 

Please update me urgently as it's already delayed much

**Comment by debinaik** [comment]
Hi Team,

Request your update please.

**Comment by TsuyoshiUshio** [comment]
Hi @debinaik 

I tried spring cloud with timer trigger. It works.  See the attached. I tested with Spring Boot and DI with autowired.
[spring-trigger.zip](https://github.com/Azure/azure-functions-java-library/files/5554917/spring-trigger.zip)

![image](https://user-images.githubusercontent.com/1390976/99420972-b885d380-28b2-11eb-8090-a0dc5731c8e1.png)

On the issue, you said "Spring azure function for timer trigger is not working. "  How "not working"?  timer trigger doesn't execute at all? or throw exception? autowired doesn't work? 

I also the organizer , however, better place to ask this issue is 

* https://github.com/Azure/azure-functions-java-worker/issues
* https://github.com/spring-cloud/spring-cloud-function/issues

I believe the kind of trigger doesn't matter.

**Comment by debinaik** [comment]
Thanks @TsuyoshiUshio . I just executed the attached code piece and encountered following error.
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
The listener for function 'Functions.hello' was unable to start.
The listener for function 'Functions.hello' was unable to start. Microsoft.Azure.Storage.Common: No connection could be made because the target machine actively re
fused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because
the target machine actively refused it.
The listener for function 'Functions.hello' was unable to start.
The listener for function 'Functions.hello' was unable to start. Microsoft.Azure.Storage.Common: No connection could be made because the target machine actively re
fused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because
the target machine actively refused it.
The listener for function 'Functions.hello' was unable to start.
The listener for function 'Functions.hello' was unable to start. Microsoft.Azure.Storage.Common: No connection could be made because the target machine actively re
fused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because
the target machine actively refused it.
The listener for function 'Functions.hello' was unable to start.
The listener for function 'Functions.hello' was unable to start. Microsoft.Azure.Storage.Common: No connection could be made because the target machine actively re
fused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because
the target machine actively refused it.
The listener for function 'Functions.hello' was unable to start.
The listener for function 'Functions.hello' was unable to start. Microsoft.Azure.Storage.Common: No connection could be made because the target machine actively re
fused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because
the target machine actively refused it

**Comment by kaibocai** [comment]
Please reopen the issue if you still have this question. Thanks.
