### ISSUE TITLE
Bind multiple query values with the same name.

### ISSUE THREAD

**Issue by peterbomers** [Azure/azure-functions-java-library#15]
Hi!

In the previous version of the library (azure-functions-java-core) bound query values with the same name resulted in a comma separated string. In the new version I only get the last found.

Example request:  https://test.azurewebsites.net/api/test?scopes=1&scopes=2

```
public static HttpResponseMessage function( final HttpRequestMessage request,  @BindingName( "scopes" ) final String scopes,  final ExecutionContext context ) {

            context.getLogger().info(scopes);
            return request.createResponse( 200, "OK" );

    }
```

Output:
previous version: "1,2"
new version: "2"

Is there a new syntax to bind multiple query values with the same name?

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1990
