### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by casper-79** [Azure/azure-functions-java-library#168]
Hi

It has been more than a year since the last release from this repo and master has been red for more than two months. Is the project dead or has it moved elsewhere?

Cheers,

Casper

**Comment by joshuapetryk** [comment]
Latest release was 2.0.0 in March of this year. See the Maven repo: https://mvnrepository.com/artifact/com.microsoft.azure.functions/azure-functions-java-library

**Comment by joshuapetryk** [comment]
FYI for anyone else looking at this: Apparently things have been ripped out and moved to https://github.com/Azure/azure-functions-java-core-library - not sure why.

**Comment by kaibocai** [comment]
We recently restructure the project, it's still living. We are using `dev` branch for development.
