### ISSUE TITLE
Warmup binding on spring cloud based application

### ISSUE THREAD

**Issue by rcastellor1** [Azure/azure-functions-java-library#176]
We are working in a spring cloud function based solution, We want to warmup the spring context with a warmupTrigger, is this posible?

The warmup trigger is documented here but I cant find any info about how to integrate it with spring cloud functions:

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-functions/functions-bindings-warmup.md

**Comment by kaibocai** [comment]
Th recent PR https://github.com/Azure/azure-functions-java-library/pull/183 adds warmup trigger. Given an example below

```
@FunctionName("Warmup")
public void warmup(@CustomBinding(direction = "in", name = "warmupContext", type = "warmupTrigger")Object warmupContext, ExecutionContext context) {
    context.getLogger().info("Function App instance is warm up");
}
```
