### ISSUE TITLE
Add support to specify partition key on EventHub output binding

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-java-library#18]
Today for C# functions if you send `EventData` type to the output binding you can define a system property for partition key which is honored when sending the message.  Today the Java output binding appears to only support string or byte [] which give no way to specify partition key

**Comment by pragnagopa** [comment]
PartitionKey is part of the metadata properties. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#trigger---event-metadata Sending a POJO with partitionkey should work.
Need to try and add E2E test.

**Comment by pragnagopa** [comment]
cc: @paulbatum

**Comment by pragnagopa** [comment]
cc @kulkarnisonia16

**Comment by pragnagopa** [comment]
Related issue on EventHubs extension: Azure/azure-sdk-for-net#28245

**Comment by pragnagopa** [comment]
given the context in  Azure/azure-sdk-for-net#28245, @amamounelsayed please sync up @alrod before finalizing structure of the EventHubMessage Type.

**Comment by fabiocav** [comment]
This is being handled with an out-of-band update. Closing as there's no action to be taken
