### ISSUE TITLE
Finish the templates for trigger, input & output binding

### ISSUE THREAD

**Issue by metacpp** [Azure/azure-functions-java-library#24]
Trigger:
--
Blob
Table
Cosmos   DB
Event   Hubs
Service   Bus Queue
Service   Bus Topic
Event   Grid
HTTP

Intput Binding
--
Blob
Table
Cosmos   DB

Output Binding
--
Blob
Table
Cosmos   DB
Event   Hubs
Service   Bus Queue
Service   Bus Topic
HTTP

**Comment by JunyiYi** [comment]
@pragnagopa , please close this issue, it is duplicated with #30 , #31 , #32 , #33 , #34 , #35 , #36 , and #37.
