### ISSUE TITLE
Improve javadoc for templates

### ISSUE THREAD

**Issue by metacpp** [Azure/azure-functions-java-library#25]
Trigger:
--
Blob
Cosmos   DB
Event   Hubs
Service   Bus Queue
Service   Bus Topic
Event   Grid

Intput Binding
--
Blob
Table
Cosmos   DB

Output Binding
--
Blob
Table
Cosmos   DB
Event   Hubs
Service   Bus Queue
Service   Bus Topic
HTTP

**Comment by selvasingh** [comment]
@rloutlaw is tracking this issue for publishing reference docs

**Comment by selvasingh** [comment]
Javadoc must exclude Java classes and interfaces that are not part of the Java API for Java functions in Azure Functions – using the “Excluding Packages” feature in Maven Javadoc plugin
https://maven.apache.org/plugins/maven-javadoc-plugin/examples/exclude-package-names.html

**Comment by JonathanGiles** [comment]
An important aspect of this documentation work is to clarify what the values should look like. I've just tried writing code that uses a BlobTrigger and I was unable to work out everything and failed.
