### ISSUE TITLE
Standardize Git Branches and Tags

### ISSUE THREAD

**Issue by brunoborges** [Azure/azure-functions-java-library#27]
It is very common practice, on GitHub and at almost all Azure/Microsoft repositories to use `master` branch as the upstream (latest working/released version) as well the *default* branch of the GitHub repository.

Tags are good to use to point to previous released versions.

For tags, the current tag name pattern is fine, perhaps just dropping 'v'. `1.0.0-beta-5` as long the Maven artifact is released under same version string.

Would be good to standardize it this way.

**Comment by pragnagopa** [comment]
Starting with the current release, version number will not be appended with "v".

**Comment by pragnagopa** [comment]
closing this as it is addressed. Dropped v  from the release tags
