### ISSUE TITLE
Add samples for Cosmos DB

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-java-library#34]
Provide Java Function code samples for - 

- [ ] Cosmos DB trigger

- [ ] Cosmos DB input

- [ ] Cosmos DB output

For reference, here is the corresponding C# code that needs to be converted to Java - 

![image](https://user-images.githubusercontent.com/8435148/43007675-e518d334-8bed-11e8-9354-2bf4bc4d60de.png)

Input examples (all required)- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#input---c-examples

Output examples (all required) - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#input---c-examples

**Comment by JunyiYi** [comment]
Runtime Error:

```
System.Private.CoreLib: One or more errors occurred. Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll' or one of its dependencies
```

**Comment by asavaritayal** [comment]
Closing as this is now done.

**Comment by pragnagopa** [comment]
Checked in
