### ISSUE TITLE
Add samples for Event Grid binding

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-java-library#36]
Provide Java Function code samples for - 

- [ ] Event Grid trigger

For reference, here is the corresponding C# code that needs to be converted to Java - 

![image](https://user-images.githubusercontent.com/8435148/43008008-ce6b9134-8bee-11e8-87d9-0b1d14819ca5.png)

**Comment by asavaritayal** [comment]
Closing as this is now done.

**Comment by pragnagopa** [comment]
Merged
