### ISSUE TITLE
Use HTTP Integer codes as the argument to createResponseBuilder() method NOT enums

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-functions-java-library#39]
I have been told this is the place to raise this (again - apologies for listing in multiple places)
Until 2.0.11933, (almost 1 YEAR), the createResponse() method signature has used an integer HTTP code. We have built functions that rely on returning non-standard (e.g. 460) Http codes for INTERNAL consumption (within out framework) only. The new method (createResponseBuilder) currently requires an enum that represents a "standard" HTTP code. It is painful enough to have to change source code to use a different method (createResponseBuilder rather than createResponse), but we MUST be able to generate Http codes rather than relying on those that MS chooses to define as an enum. While I generally agree with using enums as parameters, in this case since the enum MUST be converted back to integer for HTTP protocols, there is no compelling reason for MS to interject an enum mapping - which also has the side effect of prohibiting custom codes. If you must, put a sanity check for integers below 100 or above 1000, but please do not prohibit custom codes. I note also that anyone else who is seriously using Java Http trigger functions by necessity would have been using integers - so I don't think making the new method signature revert to integers is an issue for current developers - everyone's source code is going to have to change just to accommodate the new method.
 Thanks.
 TurtleBeach AKA -jack-

**Comment by pragnagopa** [comment]
@brunoborges  / @JonathanGiles  - Can we add an overload that can use integers for Http status codes?

**Comment by pragnagopa** [comment]
@JunyiYi

**Comment by JunyiYi** [comment]
That is the problem of using enums instead of general types. And I also remembered Paul said [WebHookType](https://github.com/Azure/azure-functions-java-library/blob/dev/src/main/java/com/microsoft/azure/functions/WebHookType.java#L31) could be any string instead of just the listed three.

@brunoborges please also change the sample code in both Javadoc and Readme file when you change any of the types or annotations. I have found several inconsistence here.

**Comment by pragnagopa** [comment]
Can we have both? Helper that takes friendly HttpStatus enum and also that accept integer?

**Comment by JunyiYi** [comment]
Of course yes, that's pretty simple.

**Comment by TurtleBeach** [comment]
Any update on this - specifically, whether it (using raw integer HTTP codes) will make it into the next release? I cannot overemphasize the importance of this. We knew we were using preview code, but never considered that we would not have direct access to specifying HTTP codes for HTTP triggered function returns - so we built a system to rely on that for a small number of non-standard codes.
@JunyiYi I am not sure I understand why a runtime exception should be thrown, even if a wild integer code is passed. Only external (to MS) developers are (a) writing the functions that return HTTP codes and (2) either writing the clients that call functions, or documenting the behavior if yet another party calls the function. In either case, I think you need to let (force?) developers be responsible for ensuring the function returns what it intends - which think means monitoring Curl or Postman responses during development. Throwing an exception will certainly get developer's attention, but may be overkill in the grand development scheme.
But that part is an aside - what I really need is to know that I will be able to generate/use non-standard HTTP return codes (sooner rather than later, since I am planning a soft launch August 1).
Thanks

**Comment by JunyiYi** [comment]
@TurtleBeach , @pragnagopa or other team members could provide more accurate timeline here.
And for the runtime exception, consider the following pseudo-code scenario:

```java
response.setStatus(HTTP.SUCCESS);
assert response.getStatus() == HTTP.SUCCESS
response.setStatusCode(444);
assert response.getStatusCode() == 444
assert response.getStatus() == EXCEPTION
```

**Comment by pragnagopa** [comment]
@TurtleBeach  - Please pin your runtime version to avoid consuming these changes. I will look into adding this overload for statuscodes during next sprint. Please feel free to send a PR if you need it sooner.

**Comment by pragnagopa** [comment]
@TurtleBeach - SNAPSHOT versions are now available to try. To try please add following in pom.xml
to use azure-functions-java-library 1.0.0-beta-7-SNAPSHOT
```
 <repositories>
        <repository>
            <id>maven.snapshots</id>
            <name>Maven Central Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

```
to use azure-functions-maven-plugin 1.0.0-beta-8-SNAPSHOT add following
```
<pluginRepositories>
        <pluginRepository>
            <id>maven.snapshots</id>
            <name>Maven Central Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```
