### ISSUE TITLE
Adding multiple entries to a storage queue via java azure function app

### ISSUE THREAD

**Issue by NickCharsley** [Azure/azure-functions-java-library#45]
From the documentation I was expecting this code 
`            @FunctionName("TestPush2")
            public HttpResponseMessage HttpTriggerJava(
                @HttpTrigger(
        		name = "req",
        		methods = {HttpMethod.GET, HttpMethod.POST},
        		authLevel = AuthorizationLevel.ANONYMOUS
		) HttpRequestMessage<Optional<String>> request,
                @QueueOutput(
                name="queue",
                queueName="queue-container",
                connection="MessageQueue"
            	) OutputBinding<String> queue,
                final ExecutionContext context) 
              {
        context.getLogger().info("Java HTTP trigger processed a request.");

        // Parse query parameter
        String query = request.getQueryParameters().get("name");
        String name = request.getBody().orElse(query);

        if (name == null) {
            return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Please pass a name on the query string or in the request body").build();
        } else {
        	queue.setValue("Echo 1");
        	queue.setValue("Echo 2");        	
            return request.createResponseBuilder(HttpStatus.OK).body("Hello, " + name).build();
        }
    }
'
to add 2 items to the queue, (like 'ICollector<string> myDestinationQueue' does in C#), however on the last Item is added.

**Comment by asavaritayal** [comment]
Started an issue for this in the worker repo - https://github.com/Azure/azure-functions-java-worker/issues/192
