### ISSUE TITLE
CosmosDBTrigger is missing important annotations

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-functions-java-library#48]
Per https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2 when using a CosmosDBTrigger, there are properties such as "leaseCollectionPrefix" which cannot be set. This particular one is very important when setting multiple trigger functions against the same CosmosDB database and collection.

Repro steps

Provide the steps required to reproduce the problem

Step A
Create a simple Java Azure Function that uses a CosmosDB trigger

Step B
Try to specify "leaseCollectionPrefix" property.

Expected behavior

All the properties as captured in https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2 can be specified.

Package version
azure-functions-java-library-1.0.0-beta-5.jar

Links to source
https://github.com/Microsoft/inventory-hub-java-on-azure/blob/master/function-apps/Notify-Inventory/src/main/java/org/inventory/hub/NotifyInventoryUpdate.java#L28

**Comment by milismsft** [comment]
see https://github.com/Azure/azure-webjobs-sdk-extensions/issues/497

**Comment by pragnagopa** [comment]
Fix checked in.
