### ISSUE TITLE
where is output Java example

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-java-library#65]
This issue is copied from https://github.com/MicrosoftDocs/azure-docs/issues/17061.
* * * 
I do not see output Java example is it supported or not?

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 6d35c032-eae7-ac4b-2ad3-32fd0cd2318f
Version Independent ID: 92b0a972-eabe-8048-36b1-a1cefb3acf43
Content: [Azure Table storage bindings for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input---java-example)
Content Source: [articles/azure-functions/functions-bindings-storage-table.md](https://github.com/Microsoft/azure-docs/blob/master/articles/azure-functions/functions-bindings-storage-table.md)
Service: azure-functions
GitHub Login: @ggailey777
Microsoft Alias: glenga

**Comment by pragnagopa** [comment]
Updated document published.
