### ISSUE TITLE
please create a gradle plugin

### ISSUE THREAD

**Issue by bastman** [Azure/azure-functions-java-library#80]
Thanks a lot for providing a maven plugin.
How about having a similar plugin for gradle?

**Comment by srmds** [comment]
Here's one : https://github.com/lenala/azure-gradle-plugins

Though not yet released to public maven repositories, waiting anxiously ;)

**Comment by srmds** [comment]
Gradle plugin is now released:
https://github.com/lenala/azure-gradle-plugins/issues/10#issuecomment-468875239

**Comment by amamounelsayed** [comment]
Thank you so much @srmds and @bastman currently you can use gradle with azure functions https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-gradle
