### ISSUE TITLE
Catching uncaught exceptions

### ISSUE THREAD

**Issue by srmds** [Azure/azure-functions-java-library#82]
My question is two-folded:

1) I would like to know if there is a notion of pre-execution and post-execution hooks, meaning:
when a function is invoked, are there hooks exposed that will be called _before and after_ the function handler is invoked?

2) Is there a way by means of a _post-hook_ to catch uncaught exceptions? If not, what alternative can I  use?

For example, if I have a function handler like below (which is written in Kotlin), what abilities can I utilise to catch an exception if one occurs, that is not explicitly caught by a try/catch block?

```kotlin
class Function {

    fun foobar(name: String?, context: ExecutionContext): String {

        // mimicking an uncaught exception
        throw Exception()

        return "Foobar"
    }
}
```

**Comment by kulkarnisonia16** [comment]
Tracking it - https://github.com/Azure/azure-functions-java-worker/issues/273
